### ISSUE TITLE
bulk-require is a bad idea

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchbay#106]
This issue is a note about my objections to bulk-require, I know I'm not currently the main maintainer, so I'm not gonna force anyone on this, but just gonna point out the problems as I see them, but I acknowledge this is not my decision.

First of all: how bulk-require bit me. I had been running v6, and then I checked out 7 and it just acted weird.
turns out, I still had a `./build` directory, which was not checked in, as a artifact of v6. But this was being included as part of bulk load, because it was part of `'!(node_modules|junk)/**/*.js'`.

In this case, it broke things, and was obvious something was wrong, but in a different situation it could have broken things in a way that wasn't obvious. It wasn't a security hole, but this is how security holes happen - it was an _unintended data flow_. I think it's much better to be completely explicit about what code is included or not.

For example, maybe later we need some scripts to do something in patchbay, and we write some scripts, maybe if you include these scripts they don't seem to do anything, but actually they introduce a security vulnerability. It doesn't look like a vulnerability when it's just run as a script, so it gets merged, but the merger forgets that it should be excluded from the bulk-require glob, because it doesn't break anything.

If it was explicit, then for the scripts directory to be added, there would have to be a commit that adds it, making it less likely it happens by accident, also this wouldn't have loaded the js in the build folder either.

I tried to change the negative glob into a positive glob that at least explicitly lists the directories to load code from, but [bulk-require](https://github.com/substack/bulk-require) doesn't even document the negative globs, so I tried a few things and it didn't work.

This is _not simple_. It's using magic not to fight dragons, or to give genuinely new capabilities, just for lazyness.

Read any fairytale, using magic for lazy reasons ends in tragedy.

The honest/explicit solution is to run bulkify manually, and check the result into git, nothing wrong with that. You always know what you are getting then.

/cc @ahdinosaur @mmckegg @mixmix

**Comment by mixmix** [comment]
Open to trying more explicit mode.

There was that script in old patchbay which did some of this right? Guess
I'm keen if there's a way which doesn't require heaps of fiddling.

The original motivation for using magic was certainly to make refactoring
less of a nightmare.

**Comment by evbogue** [comment]
I second @dominictarr on this, `bulk-require` is a bad idea. It also seems lazy to me.

**Comment by evbogue** [comment]
But what I said up there isn't very helpful. As a refresher, back when @dominictarr was working on Patchbay there was an index.js in each of the module folders that explicitly loaded each module. Then in the base of the application these individual index.js files were loaded using:

```
require('depject')(
  // from more specialized to more general
  require('./modules_extra'),
  require('./modules_basic'),
  require('./modules_core')
).app[0]()
```

**Comment by ahdinosaur** [comment]
@evbogue we have that still: https://github.com/ssbc/patchbay/blob/f7a1b7c326d2347091bb7f31ec68c4b879054f41/main.js#L15-L23.

what we're avoiding with `bulk-require` are the index files only to require all the module files, which used to be in (`./modules_core/index.js`](https://github.com/ssbc/patchbay/blob/v6/modules_core/index.js), [`./modules_basic/index.js`](https://github.com/ssbc/patchbay/blob/v6/modules_core/index.js), [`./module_extra/index.js`](https://github.com/ssbc/patchbay/blob/v6/modules_extra/index.js).

**Comment by evbogue** [comment]
Ok, so here's the `modules_core` index from Patchbay the last time @dominictarr worked on it: 

```
module.exports = {
//  "_screen_view.js":  require('./_screen_view.js'),
  "app.js":  require('./app.js'),
  "blob-url.js":  require('./blob-url.js'),
  "crypto.js":  require('./crypto.js'),
  "file-input.js":  require('./file-input.js'),
  "menu.js":  require('./menu.js'),
  "message-confirm.js":  require('./message-confirm.js'),
  "tabs.js":  require('./tabs.js'),
  "sbot.js": require('./sbot.js')
}
```

Explicit, not too hard to write up. It won't load anything you don't want. Also it makes it easier for a newcomer to the code to know what is going on.

`modules_basic` gets a little longer:
```
module.exports = {
  "about.js":  require('./about.js'),
  "avatar-edit.js":  require('./avatar-edit.js'),
  "avatar-image.js":  require('./avatar-image.js'),
  "avatar-link.js":  require('./avatar-link.js'),
  "avatar-name.js":  require('./avatar-name.js'),
  "avatar-profile.js":  require('./avatar-profile.js'),
  "avatar.js":  require('./avatar.js'),
  "compose.js":  require('./compose.js'),
  "feed.js":  require('./feed.js'),
  "follow.js":  require('./follow.js'),
  "invite.js":  require('./invite.js'),
  "like.js":  require('./like.js'),
  "markdown.js":  require('./markdown.js'),
  "message-link.js":  require('./message-link.js'),
  "message-name.js":  require('./message-name.js'),
  "message.js":  require('./message.js'),
  "names.js":  require('./names.js'),
  "post.js":  require('./post.js'),
  "private.js":  require('./private.js'),
  "pub.js":  require('./pub.js'),
  "public.js":  require('./public.js'),
  "relationships.js":  require('./relationships.js'),
  "search-box.js":  require('./search-box.js'),
  "setup.js": require('./setup'),
  "suggest-mentions.js":  require('./suggest-mentions.js'),
  "thread.js":  require('./thread.js'),
  "timestamp.js":  require('./timestamp.js')
}
```

But also, not too bad. 

Anyway, I agree with @dominictarr that _not_ being explicit about modules here could lead to compromised security for Patchbay.

**Comment by mixmix** [comment]
It's a good idea with a script to keep that up to date.
If you want to resurrect that script it would be awesome.

**Comment by evbogue** [comment]
It seems to me that the point of this discussion is _not_ to use a script to load dependencies, as that is where you get uncontrolled code flow. [See original issue](https://github.com/ssbc/patchbay/issues/106#issue-222655609).

**Comment by mixmix** [comment]
use script to create an explicit file. then can review/ pull request / see
explicit requires

**Comment by dominictarr** [comment]
@wanderer asked me why patchbay was broken... and looking at his setup (which he was git-pulling from git-ssb) and it still had some artifacts from patchbay@6 (such as module/_index.js and build/bundle.js) which was being loaded by bulk-require... so what he got was essentially 6 and 7 mashed together, which actually still kinda worked but then made weird errors and stopped working occasionally.

**Comment by mixmix** [comment]
Good to know. I wonder how they happened - that is, his did merging mean he
had leftover folders. I wonder if they're in the gitignore

**Comment by dominictarr** [comment]
he was git pulling, npm starting, which didn't clean up some of the files built back when there was a build step

**Comment by dominictarr** [comment]
sure, if you look at it's output. I figured it was probably easier to hand write it though, as I did for the PR I made.
