### ISSUE TITLE
Simplify Patchbay installation

### ISSUE THREAD

**Issue by evbogue** [ssbc/patchbay#14]
Installing Patchbay should be easier.

I did a blank install of Patchbay on another computer last night and noticed a few things.
1. Patchbay requires Patchwork to be running or images are broken. 
2. Patchbay requires Electro + Electron-prebuilt to be installed.

Both of these dependencies take a long time to download on my Internet connection in Mexico.

Is it a realistic goal to simplify installation instructions to...?

```
% sudo npm install -g scuttlebot
% sbot plugins.install ssb-links ssb-query
% sbot server
% npm start
```

This would make it easier for newcomers to get Patchbay up and running quickly.

I'm not very familiar with Electron, so I'm not sure how dependent Patchbay is on Electro(n) to function. I'm going to poke around in the code later and see if I can figure out how to achieve these goals.

**Comment by dominictarr** [comment]
agreed. we should be able to do that and then make it run in a browser.
also we havn't done anything in patchbay around initial sync.
there is currently no way to create do the invite code, etc

**Comment by dominictarr** [comment]
ultimately my goal is to have a "core" that will hardly ever change, which will include electron, sodium, leveldb, node, etc. and then have the javascript be updatable _via ssb_. not an automatic update, as we know it, but a way for people to curate new updates, and for uxers to be able to make a individual choice about who they trust to provide updates, and which update streams satisify their needs. by making it possible for users to easily make decisions about what experience they want, developers will have to listen to users, and better software will result.
more importantly, by giving users a real way to engage, and thus real power, it will hopefully expand the realm of open source to include "user applications" and thus make generic software as much _better_ as open source databases and programming languages etc are _better_ than propetiary ones currently.

**Comment by clehner** [comment]
>
% sbot plugins.install ssb-links ssb-query
% sbot server

Currently sbot has to be running for `plugins.install` to work. This could be fixed by adding a special case for it in scuttlebot's `bin.js`, or by making the install command enable what it installs automatically.

**Comment by dominictarr** [comment]
hmm, yeah. I've been installing sbot plugins manually by symlinking to by dev directories and enabling them in the config.

**Comment by du5t** [comment]
```
$ sbot plugins.install ssb-links ssb-query
TypeError: Param 1 must by of type object
Install a plugin to Scuttlebot.

install {nodeModule} [--from path]
```

oddly works if you do one plugin at a time.

**Comment by dominictarr** [comment]
@du5t yeah, that must be because of the way it wraps npm. wrapping npm was always considered a "right now" solution. it's too unreliable to depend on, in the long run (though I wish it was) but easy to start with.

**Comment by evbogue** [comment]
Leaving this one open because installing Patchbay is still hard. 

One way to simplify these instructions is to ship Scuttlebot with `ssb-ws`, `ssb-query`, and `ssb-links` already installed and loaded. That's easy, but is that something we want to do?

**Comment by dominictarr** [comment]
We nearly did that before.. but it caused some problems I think @clehner might remember?

**Comment by evbogue** [comment]
@dominictarr I think the issue is if you have `ssb-ws` installed in your plugins folder and you also load it within the `sbot/bin.js` then it'll launch two ws servers at `:8989`. At least that is the issue I've run into.

I think removing the plugin interface completely is unnecessary, but moving these plugins into core makes things a lot easier on installers. Or whatever plugins we're using to for queries in the future.

**Comment by dominictarr** [comment]
good point!

**Comment by dominictarr** [comment]
And maybe the plugin system should detect when a plugin is already loaded
and not load it twice

**Comment by pferreir** [comment]
Can it be at least mentioned in the README that one has to `npm install -g electron electro` for it to work?

**Comment by christianbundy** [comment]
I think the [current] installation instructions are about as minimal as possible, and significantly easier than they used to be. Is this ready to close?

**Comment by evbogue** [comment]
@christianbundy Yes, closing.
