### ISSUE TITLE
"right clicking" crashes app

### ISSUE THREAD

**Issue by frankiebee** [ssbc/patchbay#148]
my os: MacOsx

Not sure if this is an electron issue or an issue with patchbay but right clicking will crash the hole application. I did a quick google search and it looks like electron doesn't handle context menus gracefully or something like that not sure if thats the sole cause of the crash. 

It crashes devtools when this happens so no error in the console 

error to shell: 
```

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1e19620e2669 <String[7]: file://>
    1: add [native collection.js:~112] [pc=0x2f46c6267c0e](this=0x1e0e7bdcf189 <a Set with map 0x381c8bb06669>,q=0x2f7524283db1 <a NodeList with map 0x1a9dbe0e1a51>)
    2: valueToMeta(aka valueToMeta) [/Users/frankie/woof/patchbay/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:68] [pc=0x2f46c6210653](this=0x266e63a82311 <und...


```

Replication steps: 
- start patchbay
- right click

**Comment by Happy0** [comment]
Ha. My client crashes on right clicking too. The UI just freezes, nothing in the shell though :P

I was wondering what the source of the random crashes was until I noticed this issue.

**Comment by tomatopeel** [comment]
+1

**Comment by mixmix** [comment]
sorry about this all. @mmckegg I think I remember you mentioning debugging this for patchwork .. any insights?

**Comment by mixmix** [comment]
btw this doesn't happen if you run a standalone sbot and then start patchbay with `npm run dev` .. suggests this is electron / the rolled in sbot

**Comment by christianbundy** [comment]
My *guess* is that this is resolved, but is anyone still experiencing this bug? I'm not on macOS so I'm currently unable to test for that platform.

**Comment by mmckegg** [comment]
@christianbundy It worked last time I tried it (this month sometime).

**Comment by frankiebee** [comment]
closing issue because it has been fixed

**Comment by mixmix** [comment]
A frankie!
Hooray
