### ISSUE TITLE
direct replies to messages fork the thread (but they probably shouldn't)

### ISSUE THREAD

**Issue by mmckegg** [ssbc/patchbay#159]
I know that you've talked about this @mixmix but I just wanted to add this as an issue. 

I think an easy fix would be for replies to always copy the root of the message they are replying to. This is how it is done in patchwork: https://github.com/ssbc/patchwork/blob/master/modules/page/html/render/message.js#L71 (it's a bit of a mess in there to be honest!!)

@mixmix Would you be interested in a pull request to bring the behavior inline with patchwork?

There is definitely the case where you do want to fork a thread, though. We need to warm up that discussion again sometime!

**Comment by mixmix** [comment]
Hey my intention is to bring this inline with some work done on ticktack.

Specifically, using the fork tag in conjunction with the root tag. Root
presence implies nested reply in same thread. Root absence implies hard
fork/ different topic and space/ new thread.

This was discussed in ssb in public and dealt happy with the pattern.

Happy for PRs to implement that

**Comment by mixmix** [comment]
Thanks for the issue
