### ISSUE TITLE
Shortcut key(s) for switching through open tabs.

### ISSUE THREAD

**Issue by Happy0** [ssbc/patchbay#165]
In my web browser, I often use 'ctrl-tab' to circle through my tabs that are open.

Does such a similar keyboard shortcut exist for patchbay? If not, may I add one? :P

**Comment by cryptix** [comment]
Have you tried the vim-like bindings? Moving left and right between tabs is mapped to `h` and `l` while up down throught posts is mapped to `j` and `k`. Does this cover your needs?
