### ISSUE TITLE
Channels Appear Empty

### ISSUE THREAD

**Issue by rschulman** [ssbc/patchbay#171]
Channels that are full of messages in Patchwork appear to be empty in Patchbay. Mac OS X 10.10.5 (Yosemite). The `/public` tab does have messages in it.

**Comment by Happy0** [comment]
@rschulman how up to date are you on patchbay? I think I was having this issue until I made the following update: https://github.com/ssbc/patchbay/pull/170

Do you have the latest commit on the patchbay master branch? :)

**Comment by rschulman** [comment]
Yes, git says I'm up-to-date with origin/master.

**Comment by christianbundy** [comment]
Hey @rschulman, any chance you're still having this bug? I'm not on macOS so I'm unable to test on that platform, but I'd like to get this bug resolved for you if it's still happening.
