### ISSUE TITLE
Windows Installer trips SmartScreen

### ISSUE THREAD

**Issue by Maldaris** [ssbc/patchbay#173]
On up-to-date Windows 10, SmartScreen currently complains about the most recent release of patchbay's windows installer. Possibly to do with the fact that it does no-prompt installation, also lists unknown publisher.

**Comment by christianbundy** [comment]
Hey @Maldaris! A new version of Patchbay was just released, can you verify that the issue is continuing to happen with the Patchbay v7.14.0 installer? Thanks!

**Comment by Maldaris** [comment]
Ill get to this tonight, sure 👍

**Comment by Maldaris** [comment]
Sorry it took me forever to get back to this: corroborating @wkpatrick, Installing on Win10 Pro similarly trips SmartScreen (identical reasoning given by SmartScreen from my original experience with it).

**Comment by christianbundy** [comment]
Anyone know the solution to this? I don't run Windows, so I'm hoping this is something that electron-builder can handle for us.
