### ISSUE TITLE
close a tab on middle click

### ISSUE THREAD

**Issue by hardfire** [ssbc/patchbay#183]
Right now, middle click on a tab doesn't do anything useful. It opens some html file in the browser. 
I have created a pull request on hypertabs to close a tab on middle-click (https://github.com/hyperhype/hypertabs/pull/11). It would be pretty nice if we could get it in patchbay once merged.

PS. i am a power middle-click user :D

**Comment by christianbundy** [comment]
Hey @hardfire!

I'm now able to close with a middle-click, can you verify that it's now working for you too? Thanks!

**Comment by hardfire** [comment]
O yes! Middle click close works now!
