### ISSUE TITLE
Please display timezone on gatherings

### ISSUE THREAD

**Issue by madduck** [ssbc/patchbay#193]
It's my understanding that Patchpay displays gathering timestamps in the user's local timezone, and that's great. Nevertheless, there are certain risks here, especially when travelling timezones, and communicating with people in other timezones (e.g. cut-paste of the timestamp).

Would it be possible to simply add the local timezone identifier to the timestamp, thereby making it explicit?

**Comment by madduck** [comment]
.

**Comment by christianbundy** [comment]
@madduck I think this may have already been implemented, can you confirm that you're still having this problem?

![timezone](https://user-images.githubusercontent.com/537700/47940176-16e7e100-dea7-11e8-86d6-524e76dc0168.png)
