### ISSUE TITLE
Infinite scrolling in latest master

### ISSUE THREAD

**Issue by arj03** [ssbc/patchbay#199]
I upgraded my no-exif branch with changes from master and now I notice that in /public the same messages keeps popping up. Like it's in infinite scroll of the same 10 messages or so?

I think the last good know version for me was https://github.com/ssbc/patchbay/commit/22f68a12bbe89c31794110392cf56ce14e281c51

**Comment by arj03** [comment]
It appears to be a bug in next:

https://github.com/ssbc/patchbay/blob/439c5c1934e4781abb15490399e17e183f4e07db/app/page/public.js#L61

If I change this to:

```
      pull(
        api.feed.pull.public({reverse: true, live: false}),
        filterDownThrough(),
        Scroller(container, content, render, false, false)
      )
```

I don't get duplicates. There is a comment about rewriting this. Also next is inside a junk folder :D

**Comment by alanz** [comment]
I noticed the same behaviour ealier today.

**Comment by christianbundy** [comment]
Any chance either of you are still getting this issue? I haven't noticed it, but I want to make sure it's gone for everyone. :upside_down_face:

**Comment by alanz** [comment]
I noticed it this morning after an update from git.

But I stopped patchbay and restarted, and it has not re-occurred. So far.

Currently using ca8ac8d21e58b7d37981f6ee097ce54b1bf10b22

**Comment by alanz** [comment]
Oops, scratch that. I had an infinite scroll on mastalab today, that went away when I restarted.  Too many things.

**Comment by arj03** [comment]
It is not happening for me anymore.
