### ISSUE TITLE
private messages and inbox is buggy?

### ISSUE THREAD

**Issue by frankiebee** [ssbc/patchbay#218]
After updating patchbay i no longer get the confirm publish screen and i see the full message on my /profile which gave me a little bit of a scare because i thought i had posted a public message from inbox..

**Comment by christianbundy** [comment]
I can verify that the "confirm publish" screen isn't working on /inbox, although it's working as usual in /private. I'm not sure whether this is a bug or whether /inbox is meant to be more fast-paced and preview-free. Does anyone else know?
