### ISSUE TITLE
Node 10 incompatibility

### ISSUE THREAD

**Issue by christianbundy** [ssbc/patchbay#224]
It looks like leveldown@1.7.2 got re-added to Patchbay, which breaks anything running Node 10. Here's what I'm seeing:

```console
$ npm ls leveldown@1.7.2 
patchbay@7.13.1 /home/christianbundy/Source/patchbay
└─┬ UNMET DEPENDENCY patchbay-dark-crystal@1.0.1
  └─┬ UNMET DEPENDENCY scuttle-dark-crystal@0.1.10
    └─┬ UNMET DEPENDENCY scuttle-invite@1.0.1
      └─┬ UNMET DEPENDENCY ssb-private@0.1.4
        └─┬ UNMET DEPENDENCY flumeview-level@2.1.1
          └─┬ UNMET DEPENDENCY level@1.7.0
            └── UNMET DEPENDENCY leveldown@1.7.2
```

Hopefully we just need to bump some deps.

---

Workaround: 

```sh
rm -rf node_modules
npm install "git+https://github.com/christianbundy/scuttle-invite.git#c4eb0b4a956927109eb176769570647fcc2d42b3"
npm install
npm run rebuild
npm start
```

**Comment by christianbundy** [comment]
I think there are two paths for resolution:

- Merging #243, which is hacky but unbreaks Patchwork in Node 10 environments (all rolling release distros)
- Two-step merge and bump
  1. Merging https://github.com/ssbc/scuttle-invite/pull/8
  2. Bumping ssb-private in patchbay (and patchbay-dark-crystal (and scuttle-dark-crystal))

**Comment by mixmix** [comment]
this might be resolved (I took the two-step path)

see ssb : `%IGJPhanXEfA7PTzu13p/4miStKQWcqBUxwPLBPxm8F8=.sha256`

**Comment by christianbundy** [comment]
Oops, sorry to have left this open -- closing now. Thanks!
