### ISSUE TITLE
Posts  being passed to stdout as `Error {}`

### ISSUE THREAD

**Issue by christianbundy** [ssbc/patchbay#252]
I've noticed that in the past week or so that when I make a post it's been prepending "Error" to the object being printed. For example, I got this in the console:

```
Error {
  key: '%Iq5lNzhFcSgOYUulwqVSZQwTzTuYvUtiTNvTltWvoEQ=.sha256',
  value: 
   Error {
     previous: '%7Xl8XPhV3aFDALy0l6Xd3sAJiCFwXhW6bpvsBBZuXzk=.sha256',
     author: '@+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=.ed25519',
     sequence: 2597,
     timestamp: 1535060985623,
     hash: 'sha256',
     content: Error { type: 'vote', channel: null, vote: [Object] },
     signature: 'fddjuICFn2eANUzDuTrQgw0YRXvQDhtm9UQQJ7oxNHE1UXRzHY4Joi7TdEDi5XyU2h8rej7p2+7Sod84E0g2Cg==.sig.ed25519' },
  timestamp: 1535060985633.001 }
```

I don't think there are actually any errors, but I think maybe there's an error object being stringified somewhere. I thought the pretty printer iterated all the way through the object, but the `[Object]` bit makes me wonder whether something has changed there as well.

**Comment by cryptix** [comment]
I‘m not sure but I think pwork does this as well so it might be a pcore thing?
