### ISSUE TITLE
Can't cancel "Show my posts on public viewers"

### ISSUE THREAD

**Issue by christianbundy** [ssbc/patchbay#254]
Found a bug with the new public viewer opt-in (which is *awesome*, btw!).

1. Open /profile
2. Tick "Show my posts on public viewers"
3. Select "Cancel"

**Expected:** box is unticked and "cancel / confirm" is hidden  
**Actual:** box remains ticked and "cancel / confirm" doesn't go away

cc: @arj03

**Comment by arj03** [comment]
Thanks, fixed the same way as the other controls. They don't restore the state but that is another issue ;)
