### ISSUE TITLE
stream ended with:64 but wanted:112

### ISSUE THREAD

**Issue by christianbundy** [ssbc/patchbay#257]
I've been getting this quite a bit lately and I figure it should probably report it. Is this a Patchbay thing, or should I open an issue in [pull-reader](https://github.com/dominictarr/pull-reader)? Here's what I'm seeing:

```
server error, from net:::ffff:127.0.0.1:55366~shs:
Error: stream ended with:64 but wanted:112
    at drain (/home/christianbundy/Source/patchbay/node_modules/pull-reader/index.js:43:26)
    at /home/christianbundy/Source/patchbay/node_modules/pull-reader/index.js:63:18
    at /home/christianbundy/Source/patchbay/node_modules/pull-reader/index.js:20:7
    at /home/christianbundy/Source/patchbay/node_modules/pull-stream/throughs/through.js:19:9
    at drain (/home/christianbundy/Source/patchbay/node_modules/stream-to-pull-stream/index.js:141:18)
    at Socket.<anonymous> (/home/christianbundy/Source/patchbay/node_modules/stream-to-pull-stream/index.js:158:5)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
```

**Comment by cryptix** [comment]
This looks is an error during shs key exchange between sbot and clients. I usually only see it on my pub(s) but I guess it can happen locally when that one thread is to busy with other peers.

I don’t think there is much to report here apart from better error messages and a request for less stress full scheduling.

**Comment by christianbundy** [comment]
Thanks @cryptix. I'm wondering whether this may be a symptom of another bug. Patchbay stops pulling new content when this error is logged, so going to /posts just results in a mostly empty screen until I restart Patchbay. After the restart, everything works fine until the error happens again.

Is that normal when there's an error during shs key exchange?

**Comment by christianbundy** [comment]
Closing, not our bug.
