### ISSUE TITLE
Strange book rendering

### ISSUE THREAD

**Issue by christianbundy** [ssbc/patchbay#265]
Looks like we may have a bug in the rendering of books, not sure where to post this but I'll post screenshots. I had to `<ctrl> -` to make the text tiny to fit in as much of the page as possible.

![patchbay-small](https://user-images.githubusercontent.com/537700/47034989-b4b08180-d12d-11e8-8d5e-8830cd01d142.png)

![patchbay-small-2](https://user-images.githubusercontent.com/537700/47034988-b4b08180-d12d-11e8-91a7-615bbd621583.png)

![patchbay-small-3](https://user-images.githubusercontent.com/537700/47034986-b417eb00-d12d-11e8-9d4b-dd4912280a80.png)

**Comment by arj03** [comment]
Thanks, I have queued this up

**Comment by arj03** [comment]
Still on todo ;)
