### ISSUE TITLE
v7.15.0 changes in `config.js` don't allow connecting to an external `sbot` instance

### ISSUE THREAD

**Issue by austinfrey** [ssbc/patchbay#267]
I like to run patchbay with `npm run dev`. I _think_ the change to `config.js` makes this not work.

https://github.com/ssbc/patchbay/blob/604bfba232f38fbfe19238adda988fe86e0131d7/config.js#L28

It will throw and error.
`err? Error: connect ENOENT /home/austin/.ssb/socket`

is there a way I could just configure the `sbot` instance to allow the `noauth` connection or is this something that needs fixed in Patchbay? currently I'm just reverting that line to the previous `remote` and I'm happy to keep doing that if that's the only fix. Thanks in advance

**Comment by christianbundy** [comment]
How are you running `sbot`? If you're running scuttlebot@13.0.0 you'll need to make sure that the unix-socket and no-auth plugins are loaded (see the diff for #261). Hope that helps, I'll be happy to work through this with you.

**Comment by cryptix** [comment]
Additionally, you need to make sure there is a `connections.incoming.unix` entry in your config when you start your own sbot.

**Comment by myf** [comment]
i am getting the same problem and `unix-socket` cannot be installed (it's a package that was updated 4 years ago the last time. @christianbundy is this what you are talking about? we should make it clear for the install readme if that's the case.

**Comment by christianbundy** [comment]
@austinfrey Is this still something I can help you with?

@myf Sorry, `unix-socket` isn't a package, it's a plugin that comes with Scuttlebot. see [here](https://github.com/ssbc/patchbay/blob/0a143e40268026e6c2af2f0776882b97cf4aab25/server.js#L15) for where we add it.

**Comment by christianbundy** [comment]
No problem, just wanted to make sure I was following up. Good luck!

**Comment by austinfrey** [comment]
this works now. thanks!
