### ISSUE TITLE
hitting PgUp when composing a post obscures the page & requires restart

### ISSUE THREAD

**Issue by cameralibre** [ssbc/patchbay#268]
Patchbay-7.15.0-linux-x86_64.AppImage
Ubuntu 18.04 (Budgie Desktop)

Using PgUp & PgDn normally has the expected effect within patchbay, and still work as expected when the 'compose/reply' input is focused. However, once there is some content in the input, hitting PgUp will cut the visible space in half, make my tabs inaccessible, and make it impossible to scroll up and read the thread I was replying to (which is usually my reason for hitting PgUp in the first place). When this happens I have to copy the text I was writing, restart patchbay, navigate back to the thread and re-enter it.

![before](https://user-images.githubusercontent.com/15368010/47241591-c739fc00-d448-11e8-8fa8-0b36db1cf736.png)

![after](https://user-images.githubusercontent.com/15368010/47241596-cb661980-d448-11e8-8a2a-210e936a6f46.png)
![posts](https://user-images.githubusercontent.com/15368010/47241601-cf923700-d448-11e8-9ec3-55b081e3a413.png)

(I've used halfscreen tiling for these screenshots but the effect is the same whether halfscreen or fullscreen)

**Comment by christianbundy** [comment]
Reproduced!

![repro](https://user-images.githubusercontent.com/537700/47243373-a1f4b180-d3a6-11e8-9bcc-225009e6d5de.png)

I'm unclear on whether this is a Patchbay thing or an issue with Hypertabs, but unfortunately I'm having trouble getting the Hypertabs example going.

cc: @dominictarr @arj03 @mixmix

**Comment by christianbundy** [comment]
Btw, I know this isn't a *great* workaround but you can fix this with Ctrl+R which is slightly faster than restarting Scuttlebot + Electron. Definitely still copy your text first though!

**Comment by mixmix** [comment]
This one drives me wild. I thought is accidentally fixed out butt it's back.

One poor solution wild be to listen for pageup down keystrokes and suppress
them if context is the composer.
Other than that i guess it's searching gee dom for some weak css

**Comment by Powersource** [comment]
This is funny, patchwork has the exact same bug (see link above).

**Comment by mixmix** [comment]
Oh I fixed this (I hope!) like 327aa3ef71b44f9dd625cee6c1d06beb19a3eea4 or 2c4c4e3cda4b3f933f6aa9b718522382906636d4

@cameralibre  / @Powersource / @christianbundy  care to test and confirm? I think if one of you can't reproduce, then please close this

**Comment by cameralibre** [comment]
I can't reproduce it - looks like you squashed this one. 

🐞️🤺️ 
nice one @mixmix !

**Comment by mixmix** [comment]
thanks sam!

welcome back btw
