### ISSUE TITLE
active tab events

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchbay#27]
we need some events about which the active tab is,
so that we can do things like, detect when there is new content available on a tab
and thus mark where you have read to.

also there is a bug where there an item gets added when you are not looking at the tab,
and then you go back to the tab, and it's still in the pull-scroll queue, and when you move the scrollbar it appears. it would probably be better to appear as soon as you switch to that tab.

**Comment by clehner** [comment]
I also see the bug of items not appearing until the scrollbar is moved, but I see it on the active tab as well.

For a "new content available in tab" notification, one way would be to use DOM events. A tab could fire a custom event on its element, and `tabs.js` would catch the event when it bubbles up to the tab container, and update the tab heading. (this might involve some changes to hypertabs).

**Comment by dominictarr** [comment]
it happens in pull-scroll. pull-scroll doesn't add something if there are already 10 items, and the elements are not visible (i.e. you don't have that tab open). when you switch to that tab it should add them, but it doesn't have any way to detect that currently.
