### ISSUE TITLE
Patchbay becomes unresponsive upon NotFoundError

### ISSUE THREAD

**Issue by christianbundy** [ssbc/patchbay#271]
I clicked a link to a message and it threw an error, but when I continued using the app I realized that none of my posts were working. Searches no longer work either, which hints (maybe?) that sbot has already crashed in the background.

It's worth nothing that I'm using secure-scuttlebutt@master, but I'm unsure how long this has been a problem.

```
NotFoundError: Not Found:%atLs6tBJ6vGZCYbd42ylHbBDLK4v1BEHjlV81d6Em1w=.sha256
    at NotFound (/home/christianbundy/src/ssbc/patchbay/node_modules/flumeview-hashtable/hashtable.js:2:13)
    at next (/home/christianbundy/src/ssbc/patchbay/node_modules/flumeview-hashtable/hashtable.js:44:16)
    at /home/christianbundy/src/ssbc/patchbay/node_modules/flumeview-hashtable/hashtable.js:52:20
    at chainMaps (/home/christianbundy/src/ssbc/patchbay/node_modules/secure-scuttlebutt/minimal.js:100:14)
    at /home/christianbundy/src/ssbc/patchbay/node_modules/flumedb/index.js:71:14
    at /home/christianbundy/src/ssbc/patchbay/node_modules/flumelog-offset/inject.js:76:14
    at /home/christianbundy/src/ssbc/patchbay/node_modules/flumelog-offset/frame/recoverable.js:48:11
    at /home/christianbundy/src/ssbc/patchbay/node_modules/aligned-block-file/blocks.js:74:11
    at get (/home/christianbundy/src/ssbc/patchbay/node_modules/aligned-block-file/blocks.js:29:7)
    at next (/home/christianbundy/src/ssbc/patchbay/node_modules/aligned-block-file/blocks.js:53:7)
```

**Comment by mixmix** [comment]
There are some things you can do which seem to crash the sbot ... ? 
one example I know of is putting a weird query into `/query` ... results stop coming and you can open different pages but nothing loads

**Comment by christianbundy** [comment]
Yeah, try navigating to this non-existent message: `%zCJJlXAqwz+ESR3/UK/xeX/mrgAe2K2VJnS8XCd0ypA=.sha256`

For me, it opens the error page and then goes to that "you can open different pages but nothing loads" state. My favorite way to test this is by doing a search for `?food` or something, and when it's in this state nothing comes up. Can you reproduce the same thing on your client?

**Comment by mixmix** [comment]
This could be the routers async normalizer... getting a the message and
failing... but i wonder why it then explodes the server.
