### ISSUE TITLE
patch bay dosent connect in dev mode for me anymore

### ISSUE THREAD

**Issue by frankiebee** [ssbc/patchbay#276]
here's an error message i'm a little sleepy but opening this issue to remind my self to tell y'all this close it if it's annoying

i dont know why it's happening but i hadn't updated in awhile and then about 3 or 4 weeks ago i pulled master and this started happening 

now my sbot connection icon is red

and somewhere between now and cab191d64bed1ac52369366942b9d15937f5d785 something broke for me 

sorry this is related to the next annoying issue i open 

```
/Users/frankie/patch/bay/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron
["err?",{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"/Users/frankie/.ssb/socket"}]["unix socket client"]["err?",{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"/Users/frankie/.ssb/socket"}]["unix socket client"]["err?",{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"/Users/frankie/.ssb/socket"}]["unix socket client"]["err?",{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"/Users/frankie/.ssb/socket"}]["unix socket client"]["err?",{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"/Users/frankie/.ssb/socket"}]["unix socket client"]["err?",{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"/Users/frankie/.ssb/socket"}
```

**Comment by christianbundy** [comment]
Hey! Can you try installing straight from `package-lock.json` in master? This should look something like:

```bash
git reset --hard
npm ci
```

That *should* work, but a less-great option would be to do:

```
rm -rf node_modules
npm install
```

**Comment by frankiebee** [comment]
@christianbundy oh so many times  i have tried that

**Comment by frankiebee** [comment]
ahh seems i was running sbot and patchbay  at different node versions

**Comment by christianbundy** [comment]
Hmm. This looks like #258 to me. Maybe try this diff in `config.js`?

```diff
      config = merge(config, {
        connections: {
          incoming: { unix: [{ 'scope': 'local', 'transform': 'noauth' }] }
        },
        keys,
-        remote: `unix:${Path.join(config.path, 'socket')}:~noauth:${pubkey}`
+        remote: `net:127.0.0.1:${config.port}~shs:${pubkey}`
      })
```

cc: @arj03

**Comment by frankiebee** [comment]
jk lol i forgot i rolled back

**Comment by frankiebee** [comment]
sorry 😅

**Comment by christianbundy** [comment]
Could you try again now that #280 is merged?
