### ISSUE TITLE
not a pressing issue - `npm run dev` loads messages faster

### ISSUE THREAD

**Issue by frankiebee** [ssbc/patchbay#277]
i'll see if i can get exacts on time here to make my case but i usually like to use sbot server & npm run dev because it loads faster... why?

will investigate

**Comment by arj03** [comment]
I'm running it this way as well. If its faster then it probably has something to do with plugins having to reindex because they are a different version in patchbay normal than in your own sbot instance. Or if you move between patchwork and patchbay that they differ.
