### ISSUE TITLE
calendar does not fit on 1280x1024

### ISSUE THREAD

**Issue by Musickiller** [ssbc/patchbay#281]
The problem can be seen well on the image attached. Resolution is 1280 x 1024.

![default](https://user-images.githubusercontent.com/10563011/48471552-2e0ec300-e805-11e8-8b9c-d769e3f5d667.png)

**Comment by alanz** [comment]
Current patchbay master wraps the calendar, so I think this bug is actually resolved.

**Comment by christianbundy** [comment]
Yeah, minimum calendar width seems to be 896px, and I think *all* pages require a viewport of at least 748px to render the content. I've opened #283 for that question/documentation task, but I agree that this is resolved.

@Musickiller Could you try updating to the latest version of Patchbay? I think [the commit](https://github.com/ssbc/patchbay/commit/fcb080569f3b1f39543344c961d2df683b8b0052) should be in Patchbay v7.15.4.

**Comment by Musickiller** [comment]
> @Musickiller Could you try updating to the latest version of Patchbay? I think [the commit](https://github.com/ssbc/patchbay/commit/fcb080569f3b1f39543344c961d2df683b8b0052) should be in Patchbay v7.15.4.

I would need an .exe for that. Would you be so kind as to compile one, please? =)

**Comment by Musickiller** [comment]
I don't remember, but I think it's solved by now. Network page had the same issue, by the way.

This however may be closed.
