### ISSUE TITLE
Feature/Question: search within page

### ISSUE THREAD

**Issue by jcalfee** [ssbc/patchbay#286]
I noticed Cmd / Ctrl + F is missing for 'find in page' .. Is there another way to search for keywords within the currently shown page?

 patchbay/app/page/SHORTCUTS.md

**Comment by christianbundy** [comment]
I don't think we currently have a way to do this, it looks like there's a [module](https://github.com/rhysd/electron-in-page-search) we may be able to use though. Not sure how this would interact with hypertabs, but I'd be happy to merge a PR for this.

**Comment by jcalfee** [comment]
The module looks well supported and I'm happy to see the words auto-highlighted while typing the search.

**Comment by arj03** [comment]
This would be really nice to have :)
