### ISSUE TITLE
Color of link text makes links unreadable in /posts view

### ISSUE THREAD

**Issue by cameralibre** [ssbc/patchbay#293]
When I upgraded to patchbay-linux-7.15.6-x86_64.AppImage, I could no longer read the links in /posts view, as there is not enough contrast between the purple link color and the black background. 
![contrast](https://user-images.githubusercontent.com/15368010/49826187-2d108780-fdeb-11e8-837d-95e8263aff20.png)

I _think_ that I have a default setup, I haven't made any settings changes since the update:

![settings](https://user-images.githubusercontent.com/15368010/49826193-300b7800-fdeb-11e8-9793-ce6eb9cf5800.png)

**Comment by mplorentz** [comment]
I worked around this by adding the following css in the "Custom Styles" box:
```
a { color: #33cc33 !important }
```
