### ISSUE TITLE
Confirmed v7.15.6 runs on macOS mojave

### ISSUE THREAD

**Issue by chmac** [ssbc/patchbay#297]
This note on the release pages:

> ⚠️ warning
>
> The mac installer may not be working. Needs confirming

I've just installed on macOS mojave and it works for me.

**Comment by christianbundy** [comment]
cc: @mixmix

**Comment by mixmix** [comment]
Great, thank you!
Feel free to remove that warning anyone with priveledges

**Comment by christianbundy** [comment]
Done, thanks @chmac! :tada:
