### ISSUE TITLE
/network page clipped off

### ISSUE THREAD

**Issue by qypea** [ssbc/patchbay#301]
When trying out the new /network tab on my machine I can't see the whole graph. I'd recommend making this tab scrollable or making the graph resize to fit in the window.

![patchbay network noscroll](https://user-images.githubusercontent.com/1694406/51183914-9884c380-1887-11e9-9468-66db0ede8cdb.png)

Running 3068af308439c6051b8c9e06bc9316b15827aa23 built from source on my ubuntu 18.04 laptop.

**Comment by arj03** [comment]
Thanks for reporting. I fixed this now :)

**Comment by Musickiller** [comment]
the page is scrollable, but still clipped

![image](https://user-images.githubusercontent.com/10563011/51817843-8ec67b80-22dd-11e9-90b5-546fe4395830.png)
