### ISSUE TITLE
Add npm scripts and -g dependencies?

### ISSUE THREAD

**Issue by bcomnes** [ssbc/patchbay#31]
It seems like the 

```
npm install electro electron-prebuilt -g
electro index.js
```

stuff could be added as dependencies and an npm script to automate those steps.  

Is there a reason you didn't do that here?

**Comment by clehner** [comment]
I agree this would be good. https://www.sitepoint.com/solve-global-npm-module-dependency-problem/.
Unless we want to switch to running patchbay primarily in browsers.

**Comment by bcomnes** [comment]
Kinda running into some walls getting this working.  I'll revisit in the future.

**Comment by evbogue** [comment]
@bcomnes The Patchbay installation depends on Patchwork right now for images. Also, the chloride C compile isn't working on some systems.

I use the command

```
CHLORIDE_JS=1 electro index.js
```

To start Patchbay. You need to have Patchwork or Scuttlebot running to receive messages.

Have you tried getting Patchwork up and running yet? The experience is more robust at the moment. http://github.com/ssbc/patchwork/

**Comment by evbogue** [comment]
@bcomnes Oh, duh. You're bret on Patchwork.

**Comment by evbogue** [comment]
@clehner I'd love to figure out how to make the electro dependency optional, for people who want to run a desktop client.

**Comment by dominictarr** [comment]
adding electron as a dep makes it really heavy and takes ages to install. maybe it would be better to have a bundler repo like patchwork uses?

**Comment by dominictarr** [comment]
yeah, we need to fix images too, so they can load from somewhere else. we need this soon to make lite clients work.

**Comment by mixmix** [comment]
since electro and elctron have been folded in , I'm going to close this.

If there are outstanding issues please feel free to start a fresh issue and put the relevant questions in there
