### ISSUE TITLE
How do I make patchbay look as nice as it does in the screenshot in the README?

### ISSUE THREAD

**Issue by pospi** [ssbc/patchbay#311]
Is it using custom CSS? I'm at `v7.16.1` and it is very bare-bones, stark black & white compared to what's indicated. I have no custom CSS in my settings.

**Comment by christianbundy** [comment]
Hey @pospi, I think that's just an old screenshot.

**Comment by mixmix** [comment]
the stark black and white is my doing. It's a feature not a bug ? :cry: 

sorry you don't like the new look. You can do custom CSS, and happy to help with that if you're interested @pospi

**Comment by pospi** [comment]
I don't dislike it.. it's just... kinda Spartan. If I hadn't seen the old
screenshots I would never have even felt like something was lacking though,
FWIW <3

**Comment by mixmix** [comment]
It's the classic "is it worth another beefy blob in the repo" question
