### ISSUE TITLE
Icons are missing within the app

### ISSUE THREAD

**Issue by cinnamon-bun** [ssbc/patchbay#319]
Patchbay 7.16.1 from the github release page
OS X 10.11.6

All of the small icons within the app (hearts, checkboxes, X buttons to close things, etc) are rendered as identical squares.

![Screen Shot 2019-03-20 at 10 39 12 AM](https://user-images.githubusercontent.com/32660718/54706650-9f84b800-4afc-11e9-8abf-9280cf02c255.png)

**Comment by mixmix** [comment]
OH NO ... that's font-awesome missing ... I wonder why that's happening, I've not see that at all before.

You mean you're using an installer and this is happening right?

**Comment by cinnamon-bun** [comment]
Aha: I had renamed the app to `Patchbay 7.16.1.app` in my Applications folder.  The space in the filename is the problem.  I renamed it to `Patchbay_7.16.1.app` and the icons now work.

**Comment by ahdinosaur** [comment]
i believed this is now fixed by https://github.com/ahdinosaur/require-style/pull/6, but waiting on Patchbay to explicitly depend on the new version.
