### ISSUE TITLE
ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by austinfrey** [ssbc/patchbay#337]
patchbay version: 8.0.1
os: linux (ubuntu 18+)

```
Uncaught TypeError: Cannot read property 'stack' of null
    at base.html:27
(anonymous) @ base.html:27
```

this error throws when scrolling by this post, `%6GCB1QeCPXXnC+6YciaOfEyNBusxgUPoiDjG3mqD7CU=.sha256` in the `/posts` tab. are there more details I can provide to be more helpful?

**Comment by Happy0** [comment]
I'm running into this occasionally too.. Not sure how to reproduce it.

**Comment by arj03** [comment]
Got a few of them today. Might be related to updated mutant. I found this [issue](https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded) that describes that the error shouldn't be so severe. Still would be nice to figure out why it happens or at least filter out the error better.
