### ISSUE TITLE
a thread is automatically scrolled up

### ISSUE THREAD

**Issue by beroal** [ssbc/patchbay#346]
When I open [%ZxOfmnjQCwMnCh0TUJBmfP3oZH8ahYYwEUbH2Zk1XC8=.sha256](https://viewer.scuttlebot.io/%25ZxOfmnjQCwMnCh0TUJBmfP3oZH8ahYYwEUbH2Zk1XC8%3D.sha256) in a separate tab, I cannot scroll to replies. The page in the tab is automatically scrolled to the top message. Other threads behave normal. Probably, this is because the message contains an animated GIF.

**Comment by beroal** [comment]
The same issue with [%bAs5rzCFGFu2Qxvpm3w3R8IC45gl7Zn9su2xgv6Ubv0=.sha256](https://viewer.scuttlebot.io/%25bAs5rzCFGFu2Qxvpm3w3R8IC45gl7Zn9su2xgv6Ubv0%3D.sha256).

**Comment by beroal** [comment]
No, this issue appears if I open any discussion from my profile.

**Comment by mixmix** [comment]
I think this is a thing where it's trying to scroll to a particular message within that thread. if the message doesn't load on the page then it doesn't let go of trying to move the page, hence that terrible experience D:

**Comment by beroal** [comment]
As far as I can see, the post which I clicked on is loaded. This issue happens every time I click on a post that I **dug** in my profile, so I see to which post the link leads. (But it also happens occasionally when I click on other links in my profile.) And that post is always in the pink frame, I can’t move that frame to another post by clicking.

**Comment by mixmix** [comment]
what exactly are you clicking on in your profile. Can you take a screenshot and draw on it to indicate? 
I use keyboard shortcuts to navigate so may be taking a different path in the programming.

**Comment by beroal** [comment]
I underlined in red links that have this issue. The link starting with “xxx” does not cause me trouble because there is only one post in the thread. The links starting with “re: fork” does not have the issue.

![patchbay](https://user-images.githubusercontent.com/11978225/59960278-f8366900-94ce-11e9-829c-9fc1910a89b2.png)

**Comment by beroal** [comment]
The issue happens in other people’s profiles too.

![patchbay-2](https://user-images.githubusercontent.com/11978225/59960435-f8376880-94d0-11e9-9d4d-19ef511023b0.png)
