### ISSUE TITLE
bummer! race condition

### ISSUE THREAD

**Issue by kumavis** [ssbc/patchbay#347]
first time using `patchbay`, sometimes use `patchwork` 

my terminal looks like this, to the moon and back

```
ssb-friends#stream : bummer race condition, trying again!
ssb-friends#stream : bummer race condition, trying again!
ssb-friends#stream : bummer race condition, trying again!
ssb-friends#stream : bummer race condition, trying again!
ssb-friends#stream : bummer race condition, trying again!
ssb-friends#stream : bummer race condition, trying again!
ssb-friends#stream : bummer race condition, trying again!
ssb-friends#stream : bummer race condition, trying again!
ssb-friends#stream : bummer race condition, trying again!
ssb-friends#stream : bummer race condition, trying again!
```

**Comment by dangerousbeans** [comment]
Same for me, only once, spinning up ssb-server

**Comment by mixmix** [comment]
yep, I added that - it was a quick to a race condition. That ugly error was meant to be a poke in the eye. Looks like it worked, Dominic made a better fix : https://github.com/ssbc/ssb-friends/issues/37

It's merged, but someone needs to check if he published that, and then see if his solution works.

Either of you keen to have a go?

**Comment by mixmix** [comment]
cc @dangerousbeans @kumavis
