### ISSUE TITLE
Empty window with “electron” version 5.0.6

### ISSUE THREAD

**Issue by beroal** [ssbc/patchbay#350]
After upgrading “electron” to version 5.0.6, I see an empty windows with title “Electron” and
```
error loading sodium bindings: No native build was found for runtime=electron abi=70 platform=linuxglibc arch=x64
falling back to javascript version.
# AHOY: (main)     starting UI
```
in the terminal. After downgrading “electron” to version 4.1.4, it works again.

**Comment by christianbundy** [comment]
Does `npm install` come with electron@4? I don't think Patchbay is currently compatible with Electron 5.
