### ISSUE TITLE
Chess boards and pieces not displayed (v8.1.0)

### ISSUE THREAD

**Issue by mycognosist** [ssbc/patchbay#357]
Hey friends, I upgraded to Patchbay v8.1.0 a couple of days ago, using patchbay-Linux-8.1.0-x86_64.AppImage. The chess boards and pieces are not displayed in any of the chess tabs (Games, My Move, Invitations, Observe, Recent Activity). The chat and play-history logs are shown as normal.

Are others experiencing this?

_happy0, I know you're on holiday so please don't worry about this - just wanted to note it down._

**Comment by Happy0** [comment]
@mycognosist - aw naw. I'm guessing there might not have been a release since I fixed this on master.

Hopefully this'll be fixed whenever the next release is

**Comment by mycognosist** [comment]
@Happy0 Oh rad - glad to hear it's already sorted! I've rolled-back to the previous release for now :)
