### ISSUE TITLE
Patchbay Window Doesn't Appear When Switching Identities

### ISSUE THREAD

**Issue by madranet** [ssbc/patchbay#366]
Mac OSX 10,14,4
Patchbay: Version 8.1.0 (8.1.0)
---
I've used the `+` on the Patchbay launch/config screen to add a new Identity. 

Patchbay launches fine when I select to launch with the `ssb (default)` identity. 

![SS 2020-01-24 at 14 55 19 (2)](https://user-images.githubusercontent.com/669658/73078554-4fb01380-3eba-11ea-88c5-affc53e6d309.png)

![SS 2020-01-24 at 15 00 12](https://user-images.githubusercontent.com/669658/73078578-5b9bd580-3eba-11ea-8891-43e270a0ec70.png)

However if I select the newly created identity to launch with, I don't get an electron window at all [& no entry under Window menu]

![SS 2020-01-24 at 14 57 33 (2)](https://user-images.githubusercontent.com/669658/73078605-69515b00-3eba-11ea-9d37-3e86eb6eaa58.png)

![SS 2020-01-24 at 14 57 45](https://user-images.githubusercontent.com/669658/73078646-7bcb9480-3eba-11ea-8070-d7defbb9d78f.png)

Incidentally, in case it's relevant, the `ssb (default)` identity was setup using Patchwork before I decided to try out Patchbay. So only the 2nd identity was created using Patchbay.

**Comment by rluiten** [comment]
I am having something similar, except that an identity from patchwork or anew identity never opens a window on my machine.
My machine is Windows 10 version 1909 with updates.

**Comment by madranet** [comment]
Kinda sad that, 2 weeks later,  this pretty major usability issue hasn't even merited a response from anyone involved in the project. Looks like another one to file under "Abandonware"
