### ISSUE TITLE
keyboard shortcut malfunction

### ISSUE THREAD

**Issue by benjajuarez** [ssbc/patchbay#43]
I'm using mozilla firefox with the lite version of patchbay.

when I use many functions all is ok for closing and horizontal switch between tabs with: x, h, l

but when I try to scroll in vertical with **j,k**: it delivers _error message_:

\ el.scrollIntoViewIfNeeded is not a function

**Comment by dominictarr** [comment]
fixed in 1.7.8!

**Comment by clehner** [comment]
@dominictarr thanks, i didn't realize [scrollIntoViewIfNeeded is nonstandard](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoViewIfNeeded)
