### ISSUE TITLE
Sigil for git repos

### ISSUE THREAD

**Issue by kyrias** [ssbc/patchbay#59]
It would be useful for a new sigil to be added to look up git repos by name.

**Comment by dominictarr** [comment]
@cel what do you think?

**Comment by dominictarr** [comment]
would this just be a sigil for named messages? would just %patchbay be the right answer?

**Comment by kyrias** [comment]
That does sound like a good idea, though I wonder if a different sigil would be better, otherwise, depending on the UI, you could sort of "hijack" a message ID, hmm.

**Comment by dominictarr** [comment]
Well, that is how "@" works, it's just a name for a key. repo names already use the same format messages for naming...

can you elaborate on what you mean my "hijack"?

**Comment by kyrias** [comment]
Meant that if you name a repo the same as the message ID for another one, and you use the `%` sigil for both, then which one would be matched would depend on the client, hmm.

**Comment by dominictarr** [comment]
right, we should absolutely not allow a name to be a valid absolute identifier

**Comment by kyrias** [comment]
Yeah.  For fun I set my lite client test feed's (`@/frW8dz+HzTU17iysRq7fJxXmuBfLFSgIflfegw51ag=.ed25519`) name to `@J4TRW4y5rAW/L8WJNSruch/sN0+DRlYOGqb5s6RRalY=.ed25519`, and now if I try to type in the latter I only get the first result in the dropdown in patchbay.  And this becomes a worse problem in patchbay since the dropdown cuts off the screen, instead of being moved left to fit the whole content of it, so you don't see that it's not the proper feed ID until you go to the wrong feed and then look in the input box.

**Comment by dominictarr** [comment]
@kyrias can you screenshot that?

**Comment by kyrias** [comment]
The dropdown going off the screen?

**Comment by kyrias** [comment]
(The same happens with both the lite client and the desktop one.)

![](https://theos.kyriasis.com/~kyrias/d/dWyagWBhjB.png)

**Comment by dominictarr** [comment]
got it, hmm we can probably fix this with some CSS @evbogue what do you think?

**Comment by evbogue** [comment]
oh hey! I rarely use this Github thing anymore.

I'm seeing this issue as well. I'll fix an do a pull request on git-ssb.

**Comment by evbogue** [comment]
Fixed in: https://gitmx.com/%259xLpIhUJJUyex6MX2FHpQPwxLG0cWtaTjlWbPZriukM%3D.sha256
