### ISSUE TITLE
chloridedown sign_verify_detached mysteriously broken

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchbay#6]
I don't know why, but chloridedown doesn't verify detached signatures correctly while running inside electron! https://github.com/dominictarr/patchbay/issues/2#issuecomment-227343966

I don't know why this is happening, but the work around is:

``` js
CHLORIDE_JS=1 electro index.js
```

**Comment by dominictarr** [comment]
(use js crypto instead)

**Comment by evbogue** [comment]
This is fixed for me.

**Comment by dominictarr** [comment]
I'm gonna leave this issue open, because my solution doesn't actually fix it, just rewrites `sign_verify_detached` in terms of `sign_verify`
