### ISSUE TITLE
build failing on mac osx sierra (10.12.2) "fatal error: 'openssl/rsa.h' file not found"

### ISSUE THREAD

**Issue by fczuardi** [ssbc/patchbay#63]
I have tried to follow the README steps but couldn't complete the ```npm run rebuild``` command on a mac os 10.12.2 The build fails with this error:

```
> ursa@0.9.4 install /Users/fczuardi/github/patchbay/node_modules/ursa
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
In file included from ../src/ursaNative.cc:3:
../src/ursaNative.h:13:10: fatal error: 'openssl/rsa.h' file not found
#include <openssl/rsa.h>
```

**Comment by evbogue** [comment]
@fczuardi I think Ursa got yanked out of ssb-ws in the last version, but the package.json file hasn't been bumped to ssb-ws@1.0.1 yet. If you change the package.json to ssb-ws@1.0.1 will it build?

**Comment by fczuardi** [comment]
@evbogue yep, ```npm i --save ssb-ws@latest``` did the trick, it works, thanks!

**Comment by fczuardi** [comment]
is this issue resolved? on what commit? because today I've synced my repo with master and I had to use the same workaround again...

should we reopen this issue?

**Comment by evbogue** [comment]
@dominictarr's computer got fried, so dev slowed down a little. I think @arj03 is doing a pull for this on git-ssb.

**Comment by arj03** [comment]
Yeah, I have a open PR for that :)

**Comment by arj03** [comment]
This should be fixed now.
