### ISSUE TITLE
unable to overwrite inline styles

### ISSUE THREAD

**Issue by evbogue** [ssbc/patchbay#75]
I figured I should cross-post this here, because there seems to be a lot of activity on github.

http://viewer.scuttlebot.io/%25xH+N+IEwbMAiKYbmk38S7pKbX3NoQqmNaw27eqYk85s=.sha256

**Comment by mixmix** [comment]
@evbogue branch pushed on git-ssb for you that should help with this.

**Comment by evbogue** [comment]
The conversation continues at #86. Closing.
