### ISSUE TITLE
tab width uneven

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchbay#84]
something has broken the css that keeps the tabs evenly wide.

currently looks like this - can't tell the difference between public and private tabs

![patchbay_tabs-uneven](https://cloud.githubusercontent.com/assets/259374/22615835/ee001e54-eb02-11e6-9bf7-fc89a429ff59.png)

**Comment by mixmix** [comment]
This was  change I made. I wanted tabs that needed less space to use less space, but this case you highlight shows the downsides of that.

With fresh eyes, there's an easy intermediate solution. Published in `6.10.1`
Looks like this : 

![selection_212](https://cloud.githubusercontent.com/assets/2665886/22858217/6fac0f62-f11b-11e6-826f-e5e75fac996c.png)

:smile:
