### ISSUE TITLE
overridable styles

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchbay#86]
I want to think about how styles work in patchbay. The current way isn't working for everyone, and this is causing @evbogue to maintain a separate fork of patchbay (that isn't efficient!). ev is the vanguard of this, but there are also other projects based on tweaking patchbay (entropy, pangea) so I think this is an important thing for us to consider.

The first thing that comes to mind is that patchbay has a `mcss` socket which is called as a map (calls all `mcss` plugs), but it also has a `css` socket!

My first suggestion is to use only `css` and just have plugs which want to use `mcss` compile it themselves, and give a `css` plug only https://github.com/ssbc/patchbay/blob/master/modules_core/style/styles.js#L24 This would mean there is only one thing to think about.

The problem with calling things as a map is that there is no way to remove items. one simple solution that comes to mind immediately is to instead use a `reduce` socket. instead of just returning the css for the current module, you'd have a signature like this:

``` js
var my_style = '' //your css here, generated from mcss or whatever
module.exports = {
  gives: {css: true},
  create: function () {
    return {css: function (style) { return style + my_style }}
  }
}
```
that would mean you could have a module that just ignored every other `css` plug like this:

``` js
//no-style.js
module.exports = {
  gives: 'css',
  create: function () {
    return function (style) { return '' } //set style to empty
  }
}
```

then you'd load that in when you combine the depject modules...

``` js
require('depject')(
  require('patchbay'),
  require('./no-style'),
  require('./modules-with-new-styles')
)
```

That is one approach that would require minimal changes to the current code. I think there are a few other approaches that could work as well, and we should explore these a bit.

**Comment by dominictarr** [comment]
oh I just realized that @ahdinosaur already suggested reduce in this thread. http://viewer.scuttlebot.io/%25xH+N+IEwbMAiKYbmk38S7pKbX3NoQqmNaw27eqYk85s=.sha256#%25G54%2BFfturihfEtcIZ3L5oC5Dk1FMHOJCXc7iCYvGTAA%3D.sha256

**Comment by evbogue** [comment]
Returning to an easy theme-able Patchbay would be amazing.

How do we proceed in making this happen?

**Comment by ahdinosaur** [comment]
> an easy theme-able Patchbay

@evbogue what does this mean to you? as in, can you describe your ideal way to theme Patchbay? i'd love to help "make it happen" but i'm not sure what is wrong with our current approach and what we want instead.

**Comment by dominictarr** [comment]
@ahdinosaur I think it means to be easy to 1) use patchbay as a library, and 2) not use the current patchbay styles. it should be possible to have a completely different opinion about style - such as loading a single stylesheet (which I understand is @evbogue's preference)

**Comment by ahdinosaur** [comment]
great, thanks @dominictarr. so, how is this not addressed by overriding the [`styles` module](https://github.com/ssbc/patchbay/blob/master/modules_core/style/styles.js) with your preferred styling preference?

something like:

```js
var fs = require('fs')
var Path = require('path')

module.exports = {
  gives: { styles: true },
  create: function (api) {
    var styles = fs.readFileSync(Path.join(__dirname, 'style.css'), 'utf8'
    return { styles: function () { return styles } }
  }
}
```

**Comment by dominictarr** [comment]
right... so comparing that to the current style.js

https://github.com/ssbc/patchbay/blob/master/modules_core/style/styles.js

... which calls the `css` and `mcss` plugs and then adds them as style tags. instead, make a new style plug that simply ignores the `css` and `mcss` plugs.

**Comment by ahdinosaur** [comment]
yep! that's at least what i had in mind for anyone who wants to override the "style engine".

**Comment by evbogue** [comment]
> what does this mean to you? as in, can you describe your ideal way to theme Patchbay? i'd love to help "make it happen"

@dominictarr already answered this, but I'll just chime into to say that I agree with him. This is also how Patchbay worked before mcss was added, so we'd be returning to how things were when Patchbay was easily theme-able.

Maybe the way to go here is to make mcss optional? I think css is a sane default, because css is what most people use to style their websites.

One idea I have is to create a new library of Bay modules that are 'just the basics', without any embedded css. Then, if @ahdinosaur and @mixmix want to make their own client (or just run with the Patchbay repo) with 100% mcss they can depend on that library and also code the styles in their preferred way?

**Comment by evbogue** [comment]
When I say 'without any embedded css', I mean without any opinionated css. Pull-scroll and some other modules need embedded css to function, and this can easily an attribute in hyperscript.

**Comment by evbogue** [comment]
This is how Bay would be most useful to me, and I think other people who will develop on it in the future.

[Core] One git repo that builds an incredibly simple version of Bay that has only basic styles. 

Perhaps it could contain these modules?

```
about.js         avatar-link.js     compose.js     follow.js      invite.js    message-confirm.js  network.js        pub.js            search.js            thread.js
app.js           avatar-name.js     crypto.js      git.js         key.js       message.js          notifications.js  public.js         split.js             timestamp.js
avatar-edit.js   avatar-profile.js  emoji.js       helloworld.js  like.js      message-link.js     post.js           relationships.js  suggest-emoji.js
avatar-image.js  blob-url.js        feed.js        identify.js    markdown.js  message-name.js     private.js        sbot.js           suggest-mentions.js
avatar.js        channel.js         file-input.js  index.js       menu.js      names.js            profile-edit.js   search-box.js     tabs.js
```

**Comment by evbogue** [comment]
And then, everything else could be pushed into user-space. This way Bay is following the Node.js philosophy of 'throw everything in userspace' and get infinite awesome. This gives us maximum flexibility, and lets everyone have their own opinion about how the clients can be designed.

**Comment by mixmix** [comment]
I'm inclined to suggest not throwing out current styling. I wonder if there's a way to extract it so you don't have to see it? But also wonder why we can't just make the style module an 'extra' as Ahdinosaur suggested. 
I am up for the userland suggestion, and am in the middle of refactoring patchbay to have box models which are genuinely styleable. The mcss is only part of the story. 
 i would rather see people try to use an overide before spending time optimising

**Comment by evbogue** [comment]
@mixmix Are we having a meeting tomorrow?

I want to be able to depend on Patchbay, but you already know the reasons why I can't.

**Comment by ahdinosaur** [comment]
> I want to be able to depend on Patchbay, but you already know the reasons why I can't.

@evbogue i'm afraid i still don't understand the reasons why you can't depend on Patchbay and override the `styles` module as described [above](https://github.com/ssbc/patchbay/issues/86#issuecomment-277898815). when i continue to offer help on how you can override the current styles, but not one of these offers has been acknowledged, i feel like i'm not being listened to.

**Comment by evbogue** [comment]
I'll be on the call at the usual time tomorrow.

**Comment by mixmix** [comment]
I'll do my best to make the meeting.
Would be good to resolve this apparent block.

**Comment by ahdinosaur** [comment]
while sleeping last night, i thought of two other ways of exporting our "style modules":

```js
exports.gives = {
  css: () => ({
    Thing: `
      .Thing {
        color: green;
      }
    `
  })
}
```

where the above will be consumed as a map and merged by the consumer.

```js
exports.gives = {
  css: (styles) => assign(styles, {
    Thing: `
      .Thing {
        color: green;
      }
    `
  })
}
```

where the above will be consumed as a reduce and merged by the module.

i think this would help in overriding specific "per-component" styles, better than how it's done currently (with a `map`) or the original post suggestion (with a `reduce` of a single string).

**Comment by mmckegg** [comment]
@ahdinosaur this looks interesting! But I don't understand the syntax. How are you returning a function on a `gives`? Am I missing some important depject concept?

**Comment by ahdinosaur** [comment]
@mmckegg oops! here's a more complete (and maybe correct) example of the proposal i'm most interested in:

```js
const { assign } = Object

module.exports = {
  gives: {
    widget: true,
    mcss: true
  },
  create: (api) => {
    return {
      widget: () => {},
      mcss: (sofar) => assign(sofar, {
        Thing: `
          Thing {
            color: green
          }
        `
      })
    }
  }
}
```

```js
const { values } = Object
const compileMcss = require('micro-css')
const fs = require('fs')
const Path = require('path')

module.exports = {
  needs: {
    mcss: 'reduce',
    css: 'reduce'
  },
  gives: {
    mcss: true,
    css: true,
    styles: true
  },
  create: function (api) {
    var styles = ''
    process.nextTick(function () {
      var mcss = values(api.mcss()).join('\n')
      var css = values(api.css()).join('\n')
      styles = compileMcss(mcss) + css
    })
    return {
      styles: () => styles,
      // export empty style objects
      mcss: () => ({}),
      css: () => ({})
    }
  }
}
```

**Comment by ahdinosaur** [comment]
this way, to add or override styles for a particular widget:

```js
css: (sofar) => assign(sofar, {
  Thing: `
    .Thing {
      color: green;
    }
  `
})
```

to extend existing styles for a particular widget:

```js
css: (sofar) => assign(sofar, {
  Thing: sofar.Thing + '\n' + `
    .Thing {
      color: green;
    }
  `
})
```

to override _all_ the styles:

```js
css: (sofar) => ({
  app: fs.readFileSync('./app.css')
})
```
