### ISSUE TITLE
some backlinks don't show

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchbay#94]
In my patchbay, I'm seeing some messages show with backlinks, and others not.

for example `%G74TIna+iO1ByvYA79vNJyhd7xBiNeuDhLTmaWhBso0=.sha256` shows a backlink,
but `%4+DpwtUo+lcw4+EzW9znc4hzG8rOeRDN4MRjIb6j8kM=.sha256` does not, although there is a link to it from `%2OztgiyeuC5w2seyur3DifOscc3tV2FDmrrFlW6e08M=.sha256`. It seems to be the difference is about that I used a markdown link with text.

I always use markdown links with description because I think it will be a valuable curational signal one day

**Comment by christianbundy** [comment]
I see backlinks on both of those messages, can you verify that this is resolved for you as well? Let me know if there's anything I can do to help troubleshoot!

**Comment by dominictarr** [comment]
this is really old, am sure this is fixed now
