### ISSUE TITLE
does not understand avatar images created by patchwork@3

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchbay#97]
I noticed that this `%27s00//GQ1HOlcZboX43q8c7tWB5DnljJPFbBde/+c8=.sha256` message was showing in the feed, but not showing as the avatar for other posts by clarke. looking closer, it doesn't have a `link`
property:
```
{
  "key": "%27s00//GQ1HOlcZboX43q8c7tWB5DnljJPFbBde/+c8=.sha256",
  "value": {
    "previous": "%0dEz6DPoTXkUuRjXXmEPgJC2kNAOPqtaccMkG/RLt1Q=.sha256",
    "author": "@iii/pg320nKa62v1ohHctlhrXYPmY5BzZ1dRjypd7Cg=.ed25519",
    "sequence": 27,
    "timestamp": 1490353167852,
    "hash": "sha256",
    "content": {
      "type": "about",
      "about": "@iii/pg320nKa62v1ohHctlhrXYPmY5BzZ1dRjypd7Cg=.ed25519",
      "image": "&EjY2o1J32yYqYaGzAtr0uZEUCw7VMSSmAVTUaGVbncI=.sha256"
    },
    "signature": "M91yMd9UgJbuWYitW0SvC93yVBGPw+dfnUPiiQXspnUgwzkKQi+XMKL/e33QGDLWVHeA5LHf+9CJIhEhSrKcAA==.sig.ed25519"
  }
}
```
which makes https://github.com/ssbc/patchbay/blob/master/modules_basic/avatar/image.js#L35-L53 not detect it.

hmm, this is something that is handled by patchcore right?

**Comment by christianbundy** [comment]
Just looked up that key and it looks like it's now working correctly. Can you verify that it's working for you too? If so, can likely close this.

![screenshot from 2018-08-14 13-01-32](https://user-images.githubusercontent.com/537700/44115150-fb45b7d4-9fc1-11e8-90a0-add89bbd5cdc.png)

**Comment by dominictarr** [comment]
yeah, this is working now.
